### ISSUE TITLE
Create code-style rules for the project

### ISSUE THREAD

**Issue by feha** [ravertass/PixelHunter1995#24]
Create rules for the code-style.
ie:

- indentation

- line-breaking statements

- prefer 'this.'

- single-statement if's etc.

- and so on

Intentionally avoiding stating my opinions in this OP, better placed in whenever and wherever we end up discussing

**Comment by ravertass** [comment]
@feha Tip: Add tasks to the proejct "The Board", so they show up there. At least I primarily check tasks through The Board. :)

**Comment by feha** [comment]
There is a document in the wiki now
