### ISSUE TITLE
[BUG] When in fullscreen, the player moves where you click on the window and not the screen.

### ISSUE THREAD

**Issue by feha** [ravertass/PixelHunter1995#61]
Fullscreen does not affect the mouse-events, so the position you click does not match where it says you clicked. As a result, it is possible to make the player move outside screen.

**Comment by feha** [comment]
The window is also moved to top-left of the screen during full-screen.

**Comment by Torakko** [comment]
@feha did you start to fix this?

**Comment by Torakko** [comment]
fel knapp.... how do I unclose?

**Comment by Torakko** [comment]
hittade det :)
